Repository cloud-native-toolkit/terraform-gitops-mongo-ce-operator, pull requests merged in 2022-02, with the labels that each got.

#1 Mongo-ce gitops changes
  .github/scripts/validate-deploy.sh
  .github/workflows/manual-test-repo-delete.yaml
  .github/workflows/verify.yaml
  README.md
  chart/Chart.yaml
  chart/crds/crd.yaml
  chart/templates/configmap.yaml
  chart/templates/deployment.yaml
  chart/templates/rbac.yaml
  chart/templates/secret.yaml
  chart/values.yaml
  charts/templates/ClusterRole.yaml
  charts/templates/Deployment.yaml
  charts/templates/crd.yaml
  charts/templates/mongo-ce.yaml
  charts/templates/rbac.yaml
  charts/templates/secret.yaml
  charts/values.yaml
  main.tf
  module.yaml
  outputs.tf
  scripts/create-yaml.sh
  test/stages/stage1-gitops-bootstrap.tf
  test/stages/stage2-mongo-ce.tf
  test/stages/stage3-outputs.tf
  test/stages/variables.tf
  variables.tf
Labels: major, feature

#2 Removes CA and TLS information from operator
  chart/mongo-ce-operator/Chart.yaml
  chart/mongo-ce-operator/crds/crd.yaml
  chart/mongo-ce-operator/templates/deployment.yaml
  chart/mongo-ce-operator/templates/rbac.yaml
  chart/mongo-ce-operator/values.yaml
  chart/templates/configmap.yaml
  chart/templates/secret.yaml
  chart/values.yaml
  main.tf
  scripts/create-yaml.sh
Labels: patch, chore

#3 Adds operator to operators layer
  main.tf
Labels: patch, chore

#5 Template update changes
  .github/workflows/verify.yaml
  test/stages/stage1-cluster.tf
  test/stages/variables.tf
Labels: enhancement, patch
